icons_format = "{icon}"

[theme]
theme = "dracula"
[icons]
icons = "material-nf"
[[block]]
 block = "music"
 format = " $icon {$combo.str(max_w:10) $play $next |}"
player = "spotify"
[[block]]
block = "net"
  format = "$icon {$signal_strength ↑$graph_up ↓$graph_down $ssid} $ip"
[[block]]
block = "backlight"
device = "amdgpu_bl1"
[[block]]
block = "disk_space"
interval = 120
format = "$icon  $available"
format_alt = "$icon $used / $total - $free"
[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"
[[block]]
 block = "battery"
format = " $percentage {$time |}"
full_format = "$icon"
empty_format = "$icon"
charging_format = "O:$percentage"
not_charging_format = "icon"
device = "BAT1"
driver = "upower"
interval = 10
[[block]]
block = "time"
interval = 1
[block.format]
full = " $icon $timestamp.datetime(f:'%a %d/%m/%Y %H:%M:%S')"
